# Generated by Django 4.1.6 on 2023-02-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_skill_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='create',
            new_name='created',
        ),
    ]
