# Generated by Django 4.1.6 on 2023-02-23 10:17

from django.db import migrations, models
import vacancies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_min_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='update_at',
            field=models.DateField(null=True, validators=[vacancies.validators.check_date_not_past]),
        ),
    ]
